-- =============================================================================
-- Payment Transaction Database Schema
-- Source: Table format_Agentic_AI 1 2.xlsx (4 sheets transcribed from images)
-- Dialect: PostgreSQL (generic SQL, easy to port)
-- =============================================================================
-- Sheets / tables:
--   1. authstattab     - Authorization status (live auth decisions)
--   2. tranlogtab      - Raw transaction log messages
--   3. int_detail_tab  - Interchange / recap detail (per-charge rows)
--   4. int_control_tab - Interchange / recap control (batch header)
-- =============================================================================


-- =============================================================================
-- TABLE 1: authstattab  (Authorization Status Tab)
-- One row per authorization attempt. Populated at auth-time by the switch.
-- =============================================================================
CREATE TABLE authstattab (
    acctnum             VARCHAR(19),        -- Account number / PAN
    txndate             DATE,               -- Transaction date
    txntime             TIME,               -- Transaction time
    issuer              VARCHAR(11),        -- Issuer IIC
    acquirer            VARCHAR(11),        -- Acquirer IIC
    tracenum            VARCHAR(12),        -- System trace number (generated when the auth is initiated)
    req_amount          NUMERIC(18, 2),     -- Requested amount in local currency
    curr_code           VARCHAR(3),         -- Currency code
    issuer_amt          NUMERIC(18, 2),     -- Issuer amount
    d_amt               NUMERIC(18, 2),     -- Dollar amount (USD)
    approval_code       VARCHAR(10),        -- Issued by issuer
    mcc                 VARCHAR(4),         -- Merchant category code
    action_code         VARCHAR(4),         -- Response code (generated by issuer/network) - to check whether txn is approved or declined
    funccode            VARCHAR(4),         -- Function code - used to help us understand the nature of transaction
    add_resp            VARCHAR(50),        -- Additional response - populated by issuer/network based on CAVV, CVV, etc validation - helps in understanding decline reason
    response_time       INTEGER,            -- Time taken to complete the auth cycle (ms)
    swoutind            VARCHAR(2),         -- Switch out indicator - indicates who has taken the decision (network / issuer)
    posid               VARCHAR(15),        -- Each element in POS ID helps to identify the transaction type
    forwaiic            VARCHAR(11),        -- Forwarding IIC
    merchant_num        VARCHAR(15),        -- Merchant number
    mrch_nm             VARCHAR(50),        -- Merchant name
    mrch_str_adr        VARCHAR(100),       -- Merchant address
    mrch_cty_nm         VARCHAR(50),        -- Merchant city name
    merchant_geo_cde    VARCHAR(10),        -- Merchant geo code
    auth_type_code      VARCHAR(2),         -- Validates whether transaction is PB secured or not. '2' = PB secured, NULL = not PB secured
    nrid                VARCHAR(32),        -- Network reference ID (unique ID for each transaction)
    mti                 VARCHAR(4)          -- Message type identifier
);

COMMENT ON TABLE  authstattab IS 'Authorization status - one row per auth attempt, populated by the switch at auth-time.';
COMMENT ON COLUMN authstattab.auth_type_code IS 'PB security flag: ''2'' = PB secured; NULL = not PB secured. Referenced in the SQL-steps playbook.';
COMMENT ON COLUMN authstattab.nrid           IS 'Network Reference ID - unique per transaction, use to join across systems.';


-- =============================================================================
-- TABLE 2: tranlogtab  (Transaction Log Tab)
-- Raw transaction log; one row per switch message.
-- =============================================================================
CREATE TABLE tranlogtab (
    txndate         DATE,               -- Date
    txntime         TIME,               -- Time
    mti             VARCHAR(4),         -- Message type identifier
    rawtrans        TEXT,               -- Transaction log message which contains all the data elements delimited by <DE>
    acquirer        VARCHAR(11),        -- Acquirer IIC
    account_number  VARCHAR(19),        -- PAN
    tranlog_id      VARCHAR(32)         -- ID of each tranlog entry (unique key of this table)
);

COMMENT ON TABLE  tranlogtab IS 'Raw transaction log messages. The <DE>-delimited payload in rawtrans is the source of truth; other columns are parsed convenience fields.';
COMMENT ON COLUMN tranlogtab.rawtrans   IS 'Full switch message; data elements separated by the literal token <DE>.';
COMMENT ON COLUMN tranlogtab.tranlog_id IS 'Unique ID per tranlog row.';


-- =============================================================================
-- TABLE 3: int_detail_tab  (Interchange Detail Tab - recap line items)
-- One row per charge inside a recap batch.
-- =============================================================================
CREATE TABLE int_detail_tab (
    recap_id        VARCHAR(32),        -- Recap ID is unique ID number assigned for each recaps entry (FK -> int_control_tab.recap_id)
    charge_amount   NUMERIC(18, 2),     -- Transaction amount
    charge_date     DATE,               -- Transaction date
    type_change     VARCHAR(10),        -- Type of recap submitted
    auth_number     VARCHAR(10),        -- Same as approval_code in authstattab
    merchant_name   VARCHAR(50),        -- Establishment name
    city            VARCHAR(50),        -- City of merchant
    geocode         VARCHAR(10),        -- Geocode of merchant
    mrch_str_adr    VARCHAR(100),       -- Merchant address
    mrch_cty_nm     VARCHAR(50),        -- Merchant city name
    mcc             VARCHAR(4)          -- Merchant category code
);

COMMENT ON TABLE  int_detail_tab IS 'Recap detail rows - individual charges inside a recap batch. Joins to int_control_tab via recap_id; joins to authstattab via auth_number = approval_code.';


-- =============================================================================
-- TABLE 4: int_control_tab  (Interchange Control Tab - recap batch header)
-- One row per recap batch; aggregates debits/credits and carries settlement info.
-- =============================================================================
CREATE TABLE int_control_tab (
    acquirer_iic        VARCHAR(11),        -- Acquirer IIC
    issuer_iic          VARCHAR(11),        -- Issuer IIC
    recap_no            VARCHAR(15),        -- Number to identify the recap (sequence)
    currcode            VARCHAR(3),         -- Currency code
    recap_date          DATE,               -- Recap date
    recap_id            VARCHAR(32),        -- ID associated with each recap to uniquely identify the recap (PK)
    status              VARCHAR(20),        -- Status of each recap (whether recap was successful/processed or not)
    num_credits         INTEGER,            -- Number of transactions that were credited for that recap
    amt_credits         NUMERIC(18, 2),     -- Amount of transactions that were credited for that recap
                                            -- NOTE: the source spreadsheet description swaps 'credited' / 'debited' between
                                            -- num_* and amt_* rows; treated here by column name (amt_credits = credit amount).
    num_debits          INTEGER,            -- Number of transactions that were debited in that recap
    amt_debits          NUMERIC(18, 2),     -- Amount of transactions that were debited in that recap
    net_amt             NUMERIC(18, 2),     -- Net amount of each recap
    gross_amt           NUMERIC(18, 2),     -- Gross amount
    alt_currency        VARCHAR(3),         -- Alternate currency
    alt_gross_amt       NUMERIC(18, 2),     -- Alternate gross amount
    alt_net_amt         NUMERIC(18, 2),     -- Alternate net amount
    processing_date     DATE,               -- Processing date of recap
    settlemnt_date      DATE,               -- Settlement date of recap
    fx_rate             NUMERIC(18, 8),     -- Exchange rate applied
    fx_rate_date        DATE,               -- Date of exchange rate
    payor_stlmt_curr    VARCHAR(3),         -- Payor settlement currency
    payor_stlmnt_amt    NUMERIC(18, 2),     -- Payor settlement amount
    payee_stlmnt_curr   VARCHAR(3),         -- Payee settlement currency
    payee_stlmnt_amt    NUMERIC(18, 2),     -- Payee settlement amount
    indb_fi_id          VARCHAR(32)         -- Inbound file ID (the file in which recaps are submitted)
);

COMMENT ON TABLE  int_control_tab IS 'Recap batch header - one row per recap batch. Aggregates int_detail_tab rows and carries settlement / FX info.';
COMMENT ON COLUMN int_control_tab.amt_credits IS 'Source sheet swaps "credited"/"debited" wording in the description; column name is authoritative (credit amount).';
COMMENT ON COLUMN int_control_tab.amt_debits  IS 'See amt_credits note - column name is authoritative (debit amount).';


-- =============================================================================
-- SQL & STEPS - sample playbook captured from sheet 5
-- =============================================================================
-- Sample issue:  Check whether a given transaction is PB (PIN-Block / "PB") secured.
-- Table used:    authstattab
-- Query shape:
--   SELECT *
--     FROM xpress.authstattab
--    WHERE acctnum LIKE 'XXX%XXXX'
--      AND reqamt  = 'XXX'
--      AND txndate = 'XX-XXX-XX';
-- Interpretation:
--   - auth_type_cde = '2'   -> transaction IS PB secured
--   - auth_type_cde IS NULL -> transaction is NOT PB secured
-- Note: the sheet references column `auth_type_cde` and `reqamt`; in this schema
-- they are modeled as `auth_type_code` and `req_amount`. Rename if you need to
-- match the legacy `xpress.*` naming exactly.
-- =============================================================================
